[workspace]
authors = ["Erik van Sebille <erikvansebille@gmail.com>"]
channels = ["https://prefix.dev/parcels", "conda-forge"]
name = "MatroosParcels"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
jupyter = "jupyter"

[activation.env]
JUPYTER_CONFIG_DIR = ".jupyter"

[dependencies]
parcels = { git = "https://github.com/erikvansebille/parcels/", rev="support_nan_coords_in_hastable"}
# parcels = ">=4.0.0alpha2142,<5"
ipykernel = ">=7.2.0,<8"
jupyter = ">=1.1.1,<2"
polars = ">=1.40.0,<2"
jupyterlab = ">=4.5.7,<5"
